name: Test & Release

on:
  push:
    branches: [ release ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7.1
      uses: actions/setup-ruby@v1
      with:
        version: 2.7.x
    - name: Install dependencies
      run: bundle install
    - name: Rubocop lint check
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rspec
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
